[package]
name = "esp32-ble-tlv"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
heapless = "0.9"
log = "0.4"
sha2 = "0.10"
ed25519-dalek = "2.2"

# ESP32 (ESP-IDF + NimBLE)
esp-idf-hal = "0.45"
esp-idf-svc = "0.51"
esp32-nimble = "0.11"

[build-dependencies]
embuild = "0.33"
